default_alert_above: 55
watch_fields: 
  Humidity: 
    alert_above: 70
  Temperature: 
    alert_above: 90
    unit: ºF
  age: 
    alert_above: 0
    title: "Time since last reported measurement"
    unit: minutes
  p1: 
    alert_above: 5000
    title: "Particles >=0.3µm"
    unit: "counts per deciliter"
  p2: 
    alert_above: 2000
    title: "Particles >=0.5µm"
    unit: "counts per deciliter"
  p3: 
    alert_above: 200
    title: "Particles >=1.0µm"
    unit: "counts per deciliter"
  p4: 
    alert_above: 20
    title: "Particles >=2.5µm"
    unit: "counts per deciliter"
  p5: 
    alert_above: 10
    title: "Particles >=5.0µm"
  p6: 
    alert_above: 4
    title: "Particles >=10.0µm"
    unit: "counts per deciliter"
  pm: ~
  pm1: ~
  pm_0: ~
  pm_1: ~
  pm_10: 
    alert_above: 10
    title: "Arbitrary test value"
    unit: "counts per deciliter"
  pm_2: ~
  pm_3: ~
  pm_4: ~
  pm_5: ~
  pm_6: ~
