name: Poll Purple Air every 30 minutes
on:
  schedule:
    - cron:  '0 * * * *'
jobs:
  run-poll:
    name: Fetch Purple Air data
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
        fetch-depth: 0
    - name: run-script
      run: ruby script.rb